Edit locations in edit centers
ita-social-projects/TeachUAClient pull request #686
Opened 2023-01-03 18:29 UTC by Danbug

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-03 20:20 UTC, Vekeryk requested changes

2023-01-03 20:20 UTC, Vekeryk commented on src/components/editCenter/Description.js
> +            alert("Ви не вибрали жодного клубу")
Use ant design message instead of alert

2023-01-03 20:20 UTC, Vekeryk commented on src/components/editCenter/MainInformation.js
> +        console.log(result)
Try to avoid console.log in final commit. Remove it in other changed files if exist and close each line with ;
Also check if there unused imports

2023-01-03 20:20 UTC, Vekeryk commented on src/components/userPage/content/CenterEditModal.js
>                  let s = new Set(locationsWithDuplicates);
Should we return locationsWithoutDuplicates from API?

2023-01-03 20:20 UTC, Vekeryk commented on src/components/editCenter/Description.js
>              if(response.status && response.status ===  400 && response.data.message){
Remove catch from updateCenter service function, so you can catch any error here, intead of response.status ===  400

2023-01-03 20:20 UTC, Vekeryk commented on src/components/editCenter/Description.js
>                  window.location.reload()
Try to pass reload pagination page function in props. Do not use window.location.reload()

2023-01-03 20:20 UTC, Vekeryk commented on src/components/editCenter/Description.js
>              // nextStep();
I think nobody will return this commented code

2023-01-04 20:23 UTC, Vekeryk approved these changes

2023-01-05 09:13 UTC, softservedata approved these changes

2023-01-05 09:13 UTC, merged