Fix change clubs to go to a working endpoint
ita-social-projects/TeachUAClient pull request #688
Opened 2023-01-04 13:08 UTC by litvinchuck

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-01-04 13:17 UTC, Vekeryk requested changes

2023-01-04 13:17 UTC, Vekeryk commented on src/components/admin/club/changeOwner/ChangeOwnerFooter.js
> +        console.log(selectedRowKeys);
Remove console.log from changed files

2023-01-04 14:03 UTC, litvinchuck commented on src/components/admin/club/changeOwner/ChangeOwnerFooter.js
> +        console.log(selectedRowKeys);
👍

2023-01-04 14:05 UTC, Vekeryk approved these changes

2023-01-05 09:17 UTC, softservedata approved these changes

2023-01-05 09:17 UTC, merged